"""Add name column to task model

Revision ID: 2189bf311e7b
Revises: d891d09925fd
Create Date: 2024-11-03 02:01:59.053476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2189bf311e7b'
down_revision = 'd891d09925fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
