"""Add order column to TodoList

Revision ID: 2ce5fdcf1b71
Revises: 
Create Date: 2024-11-01 18:54:07.302302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce5fdcf1b71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('todo_list') as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
